use_frameworks!

platform :ios, '8.0'

target 'learnpods_Example' do
  pod 'learnpods', :path => '../'

  target 'learnpods_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
